name: Joke of the Day

on:
  schedule:
    - cron: "08 20 * * *"
  workflow_dispatch:

jobs:
  joke:
    runs-on: ubuntu-latest

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 24

      - run: node joke.js
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
